spring:
  application:
    name: demo
  # Rest API Configuration
  mvc:
    servlet:
      path: /api/v1

  jpa:
    hibernate:
      ddl-auto: update

  docker:
    compose:
      stop:
        command: down


